version: "3.9"
services:
  nginx:
    image: "nginx:latest"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./https.conf:/etc/nginx/conf.d/https.conf
      - ./domain.com.cert.pem:/etc/nginx/ssl/domain.com.cert.pem
      - ./domain.com.key.pem:/etc/nginx/ssl/domain.com.key.pem
    network_mode: host